environment:
  matrix:
    #- QTDIR: C:\Qt\5.11\msvc2015
    #  CMD_VCVARSALL: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x86'
    #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    #  MSVC_PLATFORM: "x86"
    - QTDIR: D:\Qt\5.9.9\msvc2017_64
      CMD_VCVARSALL: '"D:\visual Studio\VC\Auxiliary\Build\vcvarsall.bat" x64'
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      MSVC_PLATFORM: "x64"

configuration:
  - release

# Get the project submodules
# Set the environment variables and paths to make
install:
  - git submodule update --init --recursive
  - dir %QTDIR%
  - call %CMD_VCVARSALL%
  - set PATH=%PATH%;%QTDIR%\bin

# Run qmake
before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - cd DSVis
  - qmake DSVis.pro


# Build the projects
build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - cd DSVis
  - nmake
  
  
# after_build:
#   - cd %APPVEYOR_BUILD_FOLDER%
#   - cd DSVis\
#   - mkdir OurRelease\
#   - xcopy %APPVEYOR_BUILD_FOLDER%\release\DSVis.exe %APPVEYOR_BUILD_FOLDER%\DSVis\OurRelease\
#   - cd OurRelease\
#   - windeployqt DSVision.exe
#   - cd ../../
#   - 7z a %MSVC_PLATFORM%-release.zip %APPVEYOR_BUILD_FOLDER%\DSVis\OurRelease\*

# just repo root-directory
# artifacts:
#   - path: ./*-release.zip

deploy:
  provider: GitHub
  auth_token:
    secure: eZEovGqlt+IU9BefqhWyRQ==
  artifact: /.*\.zip/
  force_update: false
  on:
      branch: master
